### ISSUE TITLE
Error coming from matplotlib

### ISSUE THREAD

**Issue by molpopgen** [grahamgower/demesdraw#83]
While attempting to upload a drawing script in the demes paper, I get this with demes 0.3.0:

```
python3 drawfig.py
Traceback (most recent call last):
  File "drawfig.py", line 16, in <module>
    ax = demesdraw.tubes(graph, ax=ax, positions=positions, seed=1, inf_ratio=0.4)
  File "/home/kevin/venvs/demes_paper/lib/python3.8/site-packages/demesdraw/tubes.py", line 293, in tubes
    ax.add_patch(path_patch)
AttributeError: 'tuple' object has no attribute 'add_patch'
```

The script is this one:

```py
#!/usr/bin/env python3
import demes
import demesdraw

def size_max(graph):
    return max(
        max(epoch.start_size, epoch.end_size)
        for deme in graph.demes
        for epoch in deme.epochs
    )

graph = demes.load("models/IM.yaml")
w = 0.8 * size_max(graph)
positions = dict(A=0, X=-w, Y=w)
ax = demesdraw.utils.get_fig_axes(aspect=1)
ax = demesdraw.tubes(graph, ax=ax, positions=positions, seed=1, inf_ratio=0.4) # The offending line.
ax.figure.savefig(
    "fig/IM.pdf",
    # Save with a transparent background.
    transparent=True,
)
```

**Comment by grahamgower** [comment]
`get_fig_axes()` returns a tuple. I.e.`fig, ax = demesdraw.utils.get_fig_axes(aspect=1)`. There was an undocumented `get_axes()` function that just returned the axes, but when I chose to properly add it to the API I changed the return value (and the function name).

**Comment by molpopgen** [comment]
Thanks.
